# syntax=docker/dockerfile:1.4

FROM python:3.10.4-slim-buster

ENV TZ="Asia/Kolkata"

RUN set -euo; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get -y upgrade; \
    apt-get install gcc curl wget -y; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*;


RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -p git \
    -p 'history-substring-search' \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting \
    -a 'bindkey "\$terminfo[kcuu1]" history-substring-search-up' \
    -a 'bindkey "\$terminfo[kcud1]" history-substring-search-down';


ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_HOME="/opt/poetry" \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/app" \
    VENV_PATH="/opt/pysetup/.venv" \
    PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH" \
    POETRY_VERSION=1.1.13

RUN pip install "poetry==${POETRY_VERSION}"; \
    ln -s ${POETRY_HOME}/bin/poetry /usr/bin/poetry;

WORKDIR /src

COPY pyproject.toml .

RUN poetry config virtualenvs.create false; \
    poetry config experimental.new-installer false; \
    poetry install --no-root --no-interaction --no-ansi

EXPOSE 10338

ENTRYPOINT ["python", "manage.py", "runserver", "dev"]


