version: "3.9"
services:
  redis-service:
    image: redis/redis-stack-server:latest
    container_name: redis-container
    environment:
      REDIS_ARGS: "--appendonly yes"

    volumes:
      - type: volume
        source: redis_data
        target: /data

    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: bridge

  api-app-service:
    container_name: api-app-container

    build:
      context: .

    ports:
      - target: 10080
        published: 10080
        protocol: tcp
        mode: bridge

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pepapi.entrypoints=secure"
      - "traefik.http.routers.pepapi.entrypoints=unsecure"
      - "traefik.http.routers.pepapi.rule=Host(`pepapi.sahl.solutions`)"
      - "traefik.http.routers.pepapi.tls=true"
      - "traefik.http.routers.pepapi.tls.certresolver=primary"

    restart: unless-stopped

    depends_on:
      - redis-service


  traefik-service:
    container_name: traefik-container
    image: traefik:latest

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: bridge

      - target: 8080
        published: 8080
        protocol: tcp
        mode: bridge

    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro

    environment:
      TRAEFIK_ENTRYPOINTS_UNSECURE: "true"
      TRAEFIK_ENTRYPOINTS_UNSECURE_ADDRESS: :80

      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"

      TRAEFIK_API: "true"
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_API_INSECURE: "true"

      TRAEFIK_CERTIFICATESRESOLVERS_PRIMARY: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_PRIMARY_ACME_EMAIL: "anjum@sahl.solutions"
      TRAEFIK_CERTIFICATESRESOLVERS_PRIMARY_ACME_HTTPCHALLENGE_ENTRYPOINT: unsecure


networks:
  webapp:

volumes:
  redis_data:
    driver: local
