entryPoints:
  unsecure:
    address: :80
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
          permanent: true

  secure:
    address: :443

providers:
  file:
    directory: /etc/traefik/dynamic/
    watch: true

  docker:
    exposedByDefault: false

api:
  dashboard: true

certificatesResolvers:
  primary:
    acme:
      email: anjum@sahl.solutions
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: DEBUG
  filePath: "/var/log/traefik-logs.log"
  format: json
